# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# 博客的标题
title: WZW

# banner显示的子标题
subtitle: WZW BLOG

# banner显示的简短介绍
subtitle_desc: 日常学习与兴趣交流

# seo关键字
keywords: minfive, minfive blog, 前端博客, 前端, 程序员, 前端开发, node.js, javascript

# 博客介绍（同时用于seo）
description: 日常学习与兴趣交流的个人博客

# 个人介绍
introduction: 不思量，自难忘！

# 博客的favicon图标，支持本地及在线两种方式，本地请将图标放置于 themes/hexo-theme-skapp/source/img 目录下
favicon_ico: https://blog.static.minfive.com/other/favicon.ico

# 博客的左上角logo图标，支持本地及在线两种方式
logo: https://avatars1.githubusercontent.com/u/19220127?s=60&u=025df42ba1876d3b6971288d832bba0601d92e95&v=4

# 头像/二维码（用于显示在底部）二选一
avatar: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
# qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png

# 文章的默认封面
default_cover: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1607876703283&di=610a1af3d3fa19f0b88d44c9a1c03300&imgtype=0&src=http%3A%2F%2Fhbimg.huabanimg.com%2Fecc658501ff8e78fb1dbfcd312ea6ce5b2f7c17e1168ac-SpX7oc_fw658

# header 的背景图
header_cover: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1607876703283&di=610a1af3d3fa19f0b88d44c9a1c03300&imgtype=0&src=http%3A%2F%2Fhbimg.huabanimg.com%2Fecc658501ff8e78fb1dbfcd312ea6ce5b2f7c17e1168ac-SpX7oc_fw658

# 404 页面的背景图
error_page_bg: https://blog.static.minfive.com/other/dogs.jpg

# 页面加载loading图标
loader_img: https://blog.static.minfive.com/other/loader.gif

# 站长信息
author:
  name: WZW
  link: https://github.com/ziwen-wang
# 用于页面 footer 的站长信息
about:
  info: 本站是基于 Hexo 搭建的静态资源博客，主要用于分享日常学习、生活及工作的一些心得总结，欢迎点击右下角订阅 rss。
  address: Beijing, China
  email: wangziwen.88888@foxmail.com
# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://ziwen-wang.github.io.git
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: skapp

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/ziwen-wang/ziwen-wang.github.io.git
  branch: master

# live2 config
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/  # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false
  model:
    use: hijiki
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7
